In [167]:
import pandas as pd
import numpy as np

import  matplotlib.pyplot as plt
import seaborn as sns

In [168]:
df = pd.read_csv("Smartphone_Usage_And_Addiction_Analysis_7500_Rows.csv")
df

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,TXN07496,U07496,26,Other,9.85,1.75,3.13,3.49,5.81,249,122,11.99,Low,Yes,Moderate,1
7496,TXN07497,U07497,35,Male,5.67,2.33,2.76,5.90,8.47,197,56,7.08,Low,No,NaN,0
7497,TXN07498,U07498,22,Female,9.99,3.61,1.09,1.16,8.17,207,24,12.84,Medium,Yes,Severe,1
7498,TXN07499,U07499,23,Male,8.74,1.59,0.07,4.64,6.19,134,62,10.52,High,Yes,Severe,1
7499,TXN07500,U07500,27,Female,10.04,5.40,0.73,5.45,5.58,215,38,12.17,Low,Yes,Severe,1

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   transaction_id           7500 non-null   object
 1   user_id                  7500 non-null   object
 2   age                      7500 non-null   int64
 3   gender                   7500 non-null   object
 4   daily_screen_time_hours  7500 non-null   float64
 5   social_media_hours       7500 non-null   float64
 6   gaming_hours             7500 non-null   float64
 7   work_study_hours         7500 non-null   float64
 8   sleep_hours              7500 non-null   float64
 9   notifications_per_day    7500 non-null   int64
 10  app_opens_per_day        7500 non-null   int64
 11  weekend_screen_time      7500 non-null   float64
 12  stress_level             7500 non-null   object
 13  academic_work_impact     7500 non-null   object
 14  addiction_level          6681 non-null   object
 15  addicted_label           7500 non-null   int64
dtypes: float64(6), int64(4), object(6)
memory usage: 937.6+ KB

In [170]:
df.shape

(7500, 16)

# ML Problem Statement

#### Smartphone addiction is increasing and affecting:

- sleep quality
- mental health
- academic/work performance
- stress levels
- We want to identify users who are likely addicted to smartphones using behavioural data.


#### Goal:
- Build a Machine Learning model to predict whether a person is addicted to smartphone or not using usage behaviour and lifestyle features.

## 1 Data Cleaning

In [171]:
df.sample(10)

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
634,TXN00635,U00635,32,Male,10.16,5.34,2.48,2.37,8.72,220,21,11.80,Medium,Yes,Moderate,1
4747,TXN04748,U04748,22,Other,11.19,1.17,1.52,2.42,5.82,156,93,12.78,High,No,Moderate,1
6877,TXN06878,U06878,18,Female,7.40,3.50,0.27,1.35,5.64,172,65,9.61,High,No,Mild,0
5834,TXN05835,U05835,20,Other,4.62,5.97,0.70,1.29,6.35,35,123,7.03,Low,Yes,Moderate,1
5326,TXN05327,U05327,31,Other,6.08,4.84,1.79,4.45,7.69,86,165,8.32,High,Yes,Moderate,1
1079,TXN01080,U01080,18,Female,6.89,2.15,0.17,2.76,8.46,238,73,9.86,Low,No,Mild,0
3032,TXN03033,U03033,24,Female,7.67,5.66,1.03,2.93,7.91,79,176,8.94,Medium,No,Moderate,1
4484,TXN04485,U04485,21,Female,9.99,1.92,3.73,5.17,5.57,93,159,10.87,Medium,Yes,Severe,1
2579,TXN02580,U02580,21,Male,10.33,3.34,1.26,0.50,8.38,62,165,11.68,Medium,Yes,Moderate,1
5253,TXN05254,U05254,26,Other,11.31,1.49,1.98,5.59,7.51,130,130,12.60,High,No,Severe,1

In [172]:
# remove ID columns (not useful for prediction)

df = df.drop(columns=["transaction_id","user_id"], errors="ignore")
df

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,26,Other,9.85,1.75,3.13,3.49,5.81,249,122,11.99,Low,Yes,Moderate,1
7496,35,Male,5.67,2.33,2.76,5.90,8.47,197,56,7.08,Low,No,NaN,0
7497,22,Female,9.99,3.61,1.09,1.16,8.17,207,24,12.84,Medium,Yes,Severe,1
7498,23,Male,8.74,1.59,0.07,4.64,6.19,134,62,10.52,High,Yes,Severe,1
7499,27,Female,10.04,5.40,0.73,5.45,5.58,215,38,12.17,Low,Yes,Severe,1

In [173]:
# check duplicates

df.duplicated().sum()

np.int64(0)

In [174]:
# checking missing values 
print(df.isnull().sum())

age                          0
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             0
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          0
stress_level                 0
academic_work_impact         0
addiction_level            819
addicted_label               0
dtype: int64

In [175]:
print(df.dtypes)

age                          int64
gender                      object
daily_screen_time_hours    float64
social_media_hours         float64
gaming_hours               float64
work_study_hours           float64
sleep_hours                float64
notifications_per_day        int64
app_opens_per_day            int64
weekend_screen_time        float64
stress_level                object
academic_work_impact        object
addiction_level             object
addicted_label               int64
dtype: object

In [176]:
df.shape

(7500, 14)

## 2 Feature Engineering

In [177]:
df

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,26,Other,9.85,1.75,3.13,3.49,5.81,249,122,11.99,Low,Yes,Moderate,1
7496,35,Male,5.67,2.33,2.76,5.90,8.47,197,56,7.08,Low,No,NaN,0
7497,22,Female,9.99,3.61,1.09,1.16,8.17,207,24,12.84,Medium,Yes,Severe,1
7498,23,Male,8.74,1.59,0.07,4.64,6.19,134,62,10.52,High,Yes,Severe,1
7499,27,Female,10.04,5.40,0.73,5.45,5.58,215,38,12.17,Low,Yes,Severe,1

In [178]:
# addictive behaviour hours
df["addictive_usage_hours"] = (df["social_media_hours"] + df["gaming_hours"])
df['addictive_usage_hours']

0       2.90
1       6.05
2       5.19
3       7.36
4       9.34
        ...
7495    4.88
7496    5.09
7497    4.70
7498    1.66
7499    6.13
Name: addictive_usage_hours, Length: 7500, dtype: float64

In [179]:
df[['addictive_usage_hours','daily_screen_time_hours' ,'social_media_hours' ,'gaming_hours' ,'work_study_hours' ]]

,addictive_usage_hours,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours
0,2.90,3.23,2.01,0.89,4.55
1,6.05,5.09,3.81,2.24,4.44
2,5.19,6.06,1.36,3.83,2.35
3,7.36,7.83,5.85,1.51,3.54
4,9.34,9.96,5.92,3.42,5.27
...,...,...,...,...,...
7495,4.88,9.85,1.75,3.13,3.49
7496,5.09,5.67,2.33,2.76,5.90
7497,4.70,9.99,3.61,1.09,1.16
7498,1.66,8.74,1.59,0.07,4.64
7499,6.13,10.04,5.40,0.73,5.45

In [180]:
# addiction intensity ratio
df["addiction_usage_ratio"] = (df["addictive_usage_hours"]/ df["daily_screen_time_hours"])
df['addiction_usage_ratio']

0       0.897833
1       1.188605
2       0.856436
3       0.939974
4       0.937751
          ...
7495    0.495431
7496    0.897707
7497    0.470470
7498    0.189931
7499    0.610558
Name: addiction_usage_ratio, Length: 7500, dtype: float64

In [181]:
df[['addiction_usage_ratio', 'addictive_usage_hours','daily_screen_time_hours']]

      addiction_usage_ratio  addictive_usage_hours  daily_screen_time_hours
0                  0.897833                   2.90                     3.23
1                  1.188605                   6.05                     5.09
2                  0.856436                   5.19                     6.06
3                  0.939974                   7.36                     7.83
4                  0.937751                   9.34                     9.96
...                     ...                    ...                      ...
7495               0.495431                   4.88                     9.85
7496               0.897707                   5.09                     5.67
7497               0.470470                   4.70                     9.99
7498               0.189931                   1.66                     8.74
7499               0.610558                   6.13                    10.04

[7500 rows x 3 columns]

In [182]:

# fix unrealistic values
df["addiction_usage_ratio"] = df["addiction_usage_ratio"].clip(0,1)

df[['addiction_usage_ratio', 'addictive_usage_hours','daily_screen_time_hours']]

      addiction_usage_ratio  addictive_usage_hours  daily_screen_time_hours
0                  0.897833                   2.90                     3.23
1                  1.000000                   6.05                     5.09
2                  0.856436                   5.19                     6.06
3                  0.939974                   7.36                     7.83
4                  0.937751                   9.34                     9.96
...                     ...                    ...                      ...
7495               0.495431                   4.88                     9.85
7496               0.897707                   5.09                     5.67
7497               0.470470                   4.70                     9.99
7498               0.189931                   1.66                     8.74
7499               0.610558                   6.13                    10.04

[7500 rows x 3 columns]

In [183]:
df["addiction_usage_ratio"].describe()

count    7500.000000
mean        0.695455
std         0.260059
min         0.047819
25%         0.486932
50%         0.702838
75%         1.000000
max         1.000000
Name: addiction_usage_ratio, dtype: float64

In [184]:
# sleep impact
df["sleep_deficit"] = 8 - df["sleep_hours"]
df[['sleep_deficit' , 'sleep_hours']]

      sleep_deficit  sleep_hours
0              0.45         7.55
1              0.34         7.66
2              3.08         4.92
3             -0.23         8.23
4              1.79         6.21
...             ...          ...
7495           2.19         5.81
7496          -0.47         8.47
7497          -0.17         8.17
7498           1.81         6.19
7499           2.42         5.58

[7500 rows x 2 columns]

In [185]:

# weekend behaviour change
df["weekend_usage_diff"] = (df["weekend_screen_time"]- df["daily_screen_time_hours"])

df[['weekend_usage_diff','weekend_screen_time','daily_screen_time_hours']]

      weekend_usage_diff  weekend_screen_time  daily_screen_time_hours
0                   0.72                 3.95                     3.23
1                   1.62                 6.71                     5.09
2                   2.62                 8.68                     6.06
3                   1.94                 9.77                     7.83
4                   2.59                12.55                     9.96
...                  ...                  ...                      ...
7495                2.14                11.99                     9.85
7496                1.41                 7.08                     5.67
7497                2.85                12.84                     9.99
7498                1.78                10.52                     8.74
7499                2.13                12.17                    10.04

[7500 rows x 3 columns]

## 3 Train Test Split

In [186]:
df

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0,2.90,0.897833,0.45,0.72
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0,6.05,1.000000,0.34,1.62
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0,5.19,0.856436,3.08,2.62
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1,7.36,0.939974,-0.23,1.94
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1,9.34,0.937751,1.79,2.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,26,Other,9.85,1.75,3.13,3.49,5.81,249,122,11.99,Low,Yes,Moderate,1,4.88,0.495431,2.19,2.14
7496,35,Male,5.67,2.33,2.76,5.90,8.47,197,56,7.08,Low,No,NaN,0,5.09,0.897707,-0.47,1.41
7497,22,Female,9.99,3.61,1.09,1.16,8.17,207,24,12.84,Medium,Yes,Severe,1,4.70,0.470470,-0.17,2.85
7498,23,Male,8.74,1.59,0.07,4.64,6.19,134,62,10.52,High,Yes,Severe,1,1.66,0.189931,1.81,1.78
7499,27,Female,10.04,5.40,0.73,5.45,5.58,215,38,12.17,Low,Yes,Severe,1,6.13,0.610558,2.42,2.13

In [187]:
from sklearn.model_selection import train_test_split

In [188]:
X = df.drop("addicted_label", axis=1)
y = df["addicted_label"]

In [189]:
X

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,2.90,0.897833,0.45,0.72
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,6.05,1.000000,0.34,1.62
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,5.19,0.856436,3.08,2.62
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,7.36,0.939974,-0.23,1.94
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,9.34,0.937751,1.79,2.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,26,Other,9.85,1.75,3.13,3.49,5.81,249,122,11.99,Low,Yes,Moderate,4.88,0.495431,2.19,2.14
7496,35,Male,5.67,2.33,2.76,5.90,8.47,197,56,7.08,Low,No,NaN,5.09,0.897707,-0.47,1.41
7497,22,Female,9.99,3.61,1.09,1.16,8.17,207,24,12.84,Medium,Yes,Severe,4.70,0.470470,-0.17,2.85
7498,23,Male,8.74,1.59,0.07,4.64,6.19,134,62,10.52,High,Yes,Severe,1.66,0.189931,1.81,1.78
7499,27,Female,10.04,5.40,0.73,5.45,5.58,215,38,12.17,Low,Yes,Severe,6.13,0.610558,2.42,2.13

In [190]:
y

0       0
1       0
2       0
3       1
4       1
       ..
7495    1
7496    0
7497    1
7498    1
7499    1
Name: addicted_label, Length: 7500, dtype: int64

In [191]:
# spliting data

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2,random_state = 42,stratify = y )

In [192]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (6000, 17)
X_test: (1500, 17)
y_train: (6000,)
y_test: (1500,)

# 4 Preprocessing

In [193]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [194]:
df

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0,2.90,0.897833,0.45,0.72
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0,6.05,1.000000,0.34,1.62
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0,5.19,0.856436,3.08,2.62
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1,7.36,0.939974,-0.23,1.94
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1,9.34,0.937751,1.79,2.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,26,Other,9.85,1.75,3.13,3.49,5.81,249,122,11.99,Low,Yes,Moderate,1,4.88,0.495431,2.19,2.14
7496,35,Male,5.67,2.33,2.76,5.90,8.47,197,56,7.08,Low,No,NaN,0,5.09,0.897707,-0.47,1.41
7497,22,Female,9.99,3.61,1.09,1.16,8.17,207,24,12.84,Medium,Yes,Severe,1,4.70,0.470470,-0.17,2.85
7498,23,Male,8.74,1.59,0.07,4.64,6.19,134,62,10.52,High,Yes,Severe,1,1.66,0.189931,1.81,1.78
7499,27,Female,10.04,5.40,0.73,5.45,5.58,215,38,12.17,Low,Yes,Severe,1,6.13,0.610558,2.42,2.13

In [195]:
# numerical columns
num_cols = X_train.select_dtypes(include=["int64","float64"]).columns

# categorical columns
cat_cols = X_train.select_dtypes(include=["object"]).columns

In [196]:
cat_cols

Index(['gender', 'stress_level', 'academic_work_impact', 'addiction_level'], dtype='object')

In [197]:
num_cols

Index(['age', 'daily_screen_time_hours', 'social_media_hours', 'gaming_hours',
       'work_study_hours', 'sleep_hours', 'notifications_per_day',
       'app_opens_per_day', 'weekend_screen_time', 'addictive_usage_hours',
       'addiction_usage_ratio', 'sleep_deficit', 'weekend_usage_diff'],
      dtype='object')

In [198]:
X_train.isnull().sum()

age                          0
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             0
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          0
stress_level                 0
academic_work_impact         0
addiction_level            647
addictive_usage_hours        0
addiction_usage_ratio        0
sleep_deficit                0
weekend_usage_diff           0
dtype: int64

In [199]:
# handling missing values
from sklearn.impute import SimpleImputer

In [200]:
X_train[cat_cols].isnull().sum()

gender                    0
stress_level              0
academic_work_impact      0
addiction_level         647
dtype: int64

In [201]:
# categorical imputer
cat_imputer = SimpleImputer(strategy="most_frequent")
cat_imputer

SimpleImputer(strategy='most_frequent')

In [202]:
X_train[cat_cols] = cat_imputer.fit_transform(X_train[cat_cols])

## Encoding categorical columns

In [203]:
cat_cols

Index(['gender', 'stress_level', 'academic_work_impact', 'addiction_level'], dtype='object')

In [204]:
X_train[cat_cols]

      gender stress_level academic_work_impact addiction_level
5171  Female       Medium                  Yes        Moderate
6534   Other         High                  Yes        Moderate
1737    Male          Low                  Yes          Severe
3749   Other         High                  Yes        Moderate
63    Female          Low                   No          Severe
...      ...          ...                  ...             ...
1359    Male         High                   No        Moderate
2844   Other         High                   No          Severe
5819  Female          Low                  Yes        Moderate
4487  Female         High                  Yes            Mild
6555    Male         High                   No            Mild

[6000 rows x 4 columns]

In [205]:
# Ordinal columns
# ["stress_level","academic_work_impact","addiction_level"]

from sklearn.preprocessing import OrdinalEncoder

In [206]:
X_train["stress_level"].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [207]:
X_train['academic_work_impact'].unique()

array(['Yes', 'No'], dtype=object)

In [208]:
X_train['addiction_level'].unique()

array(['Moderate', 'Severe', 'Mild'], dtype=object)

In [209]:
ordinal_cols = ["stress_level","addiction_level"]

X_train[ordinal_cols]

     stress_level addiction_level
5171       Medium        Moderate
6534         High        Moderate
1737          Low          Severe
3749         High        Moderate
63            Low          Severe
...           ...             ...
1359         High        Moderate
2844         High          Severe
5819          Low        Moderate
4487         High            Mild
6555         High            Mild

[6000 rows x 2 columns]

In [210]:
ordinal_order = [
    ["Low","Medium","High"],
    ["Mild","Moderate","Severe"]
]

ordinal_encoder = OrdinalEncoder(categories=ordinal_order)
ordinal_encoder

OrdinalEncoder(categories=[['Low', 'Medium', 'High'],
                           ['Mild', 'Moderate', 'Severe']])

In [211]:
X_train[ordinal_cols] = ordinal_encoder.fit_transform(X_train[ordinal_cols])

In [212]:
X_train[ordinal_cols]

      stress_level  addiction_level
5171           1.0              1.0
6534           2.0              1.0
1737           0.0              2.0
3749           2.0              1.0
63             0.0              2.0
...            ...              ...
1359           2.0              1.0
2844           2.0              2.0
5819           0.0              1.0
4487           2.0              0.0
6555           2.0              0.0

[6000 rows x 2 columns]

In [213]:
X_train['stress_level'].unique()

array([1., 2., 0.])

In [214]:
X_train.addiction_level.unique()

array([1., 2., 0.])

In [215]:
X_train["academic_work_impact"]

5171    Yes
6534    Yes
1737    Yes
3749    Yes
63       No
       ...
1359     No
2844     No
5819    Yes
4487    Yes
6555     No
Name: academic_work_impact, Length: 6000, dtype: object

In [216]:
X_train["academic_work_impact"] = X_train["academic_work_impact"].map({ "No":0,"Yes":1})

In [217]:
X_train["academic_work_impact"]

5171    1
6534    1
1737    1
3749    1
63      0
       ..
1359    0
2844    0
5819    1
4487    1
6555    0
Name: academic_work_impact, Length: 6000, dtype: int64

In [218]:
X_train[cat_cols]

      gender  stress_level  academic_work_impact  addiction_level
5171  Female           1.0                     1              1.0
6534   Other           2.0                     1              1.0
1737    Male           0.0                     1              2.0
3749   Other           2.0                     1              1.0
63    Female           0.0                     0              2.0
...      ...           ...                   ...              ...
1359    Male           2.0                     0              1.0
2844   Other           2.0                     0              2.0
5819  Female           0.0                     1              1.0
4487  Female           2.0                     1              0.0
6555    Male           2.0                     0              0.0

[6000 rows x 4 columns]

### Ohe Hot Encoding

In [219]:
X_train['gender']

5171    Female
6534     Other
1737      Male
3749     Other
63      Female
         ...
1359      Male
2844     Other
5819    Female
4487    Female
6555      Male
Name: gender, Length: 6000, dtype: object

In [220]:
from sklearn.preprocessing import OneHotEncoder

In [221]:
onehot_encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
onehot_encoder

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [222]:
gender_encoded = onehot_encoder.fit_transform(X_train[["gender"]])
gender_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], shape=(6000, 3))

In [223]:

gender_df = pd.DataFrame(gender_encoded,
                         columns=onehot_encoder.get_feature_names_out(["gender"]),
                         index=X_train.index)

X_train = X_train.drop(columns=["gender"])

X_train = pd.concat([X_train, gender_df], axis=1)

In [224]:
X_train

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff,gender_Female,gender_Male,gender_Other
5171,31,5.17,4.16,2.38,4.11,8.33,212,41,5.94,1.0,1,1.0,6.54,1.000000,-0.33,0.77,1.0,0.0,0.0
6534,32,9.65,5.38,1.59,3.59,5.93,150,170,10.42,2.0,1,1.0,6.97,0.722280,2.07,0.77,0.0,0.0,1.0
1737,25,9.64,1.74,1.85,1.37,7.91,66,153,12.29,0.0,1,2.0,3.59,0.372407,0.09,2.65,0.0,1.0,0.0
3749,31,6.94,3.94,1.53,2.05,6.78,180,74,7.53,2.0,1,1.0,5.47,0.788184,1.22,0.59,0.0,0.0,1.0
63,20,5.06,4.21,3.44,3.73,4.59,215,83,7.00,0.0,0,2.0,7.65,1.000000,3.41,1.94,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1359,24,10.85,3.64,3.71,1.01,8.01,184,162,11.77,2.0,0,1.0,7.35,0.677419,-0.01,0.92,0.0,1.0,0.0
2844,18,4.52,4.87,1.12,5.71,8.70,32,128,6.30,2.0,0,2.0,5.99,1.000000,-0.70,1.78,0.0,0.0,1.0
5819,23,5.93,3.02,0.98,2.92,6.24,217,81,7.80,0.0,1,1.0,4.00,0.674536,1.76,1.87,1.0,0.0,0.0
4487,21,4.61,3.50,0.76,5.38,5.38,23,34,6.28,2.0,1,0.0,4.26,0.924078,2.62,1.67,1.0,0.0,0.0
6555,27,6.83,1.68,3.04,2.16,6.92,206,88,9.41,2.0,0,0.0,4.72,0.691069,1.08,2.58,0.0,1.0,0.0

### scaling numerical features

In [225]:
X_train[num_cols]

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
5171,31,5.17,4.16,2.38,4.11,8.33,212,41,5.94,6.54,1.000000,-0.33,0.77
6534,32,9.65,5.38,1.59,3.59,5.93,150,170,10.42,6.97,0.722280,2.07,0.77
1737,25,9.64,1.74,1.85,1.37,7.91,66,153,12.29,3.59,0.372407,0.09,2.65
3749,31,6.94,3.94,1.53,2.05,6.78,180,74,7.53,5.47,0.788184,1.22,0.59
63,20,5.06,4.21,3.44,3.73,4.59,215,83,7.00,7.65,1.000000,3.41,1.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1359,24,10.85,3.64,3.71,1.01,8.01,184,162,11.77,7.35,0.677419,-0.01,0.92
2844,18,4.52,4.87,1.12,5.71,8.70,32,128,6.30,5.99,1.000000,-0.70,1.78
5819,23,5.93,3.02,0.98,2.92,6.24,217,81,7.80,4.00,0.674536,1.76,1.87
4487,21,4.61,3.50,0.76,5.38,5.38,23,34,6.28,4.26,0.924078,2.62,1.67
6555,27,6.83,1.68,3.04,2.16,6.92,206,88,9.41,4.72,0.691069,1.08,2.58

In [226]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler

StandardScaler()

In [227]:
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_train[num_cols]

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
5171,0.845647,-0.890757,0.566001,0.317139,0.538647,1.238562,1.161997,-1.167484,-1.213161,0.644997,1.170364,-1.238562,-1.351359
6534,1.037869,0.830243,1.333188,-0.371107,0.213916,-0.631536,0.232537,1.491283,0.437582,0.864402,0.104642,0.631536,-1.351359
1737,-0.307683,0.826402,-0.955797,-0.144596,-1.172436,0.911295,-1.026731,1.140903,1.126620,-0.860223,-1.237961,-0.911295,1.257898
3749,0.845647,-0.210809,0.427655,-0.423379,-0.747788,0.030790,0.682276,-0.487334,-0.627295,0.099036,0.357544,-0.030790,-1.601182
63,-1.268791,-0.933014,0.597443,1.240609,0.301343,-1.675675,1.206971,-0.301839,-0.822583,1.211367,1.170364,1.675675,0.272487
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1359,-0.499905,1.291226,0.239003,1.475833,-1.397250,0.989216,0.742241,1.326398,0.935016,1.058294,-0.067506,-0.989216,-1.143174
2844,-1.653235,-1.140456,1.012478,-0.780570,1.537819,1.526869,-1.536435,0.625638,-1.080512,0.364363,1.170364,-1.526869,0.050423
5819,-0.692126,-0.598802,-0.150879,-0.902538,-0.204488,-0.389982,1.236954,-0.343060,-0.527808,-0.651023,-0.078569,0.389982,0.175334
4487,-1.076570,-1.105883,0.150965,-1.094202,1.331740,-1.060100,-1.671356,-1.311758,-1.087881,-0.518359,0.879022,1.060100,-0.102247
6555,0.076761,-0.253065,-0.993527,0.892130,-0.679095,0.139879,1.072050,-0.198786,0.065428,-0.283647,-0.015127,-0.139879,1.160745

## 5 Apply preprocessing on test data

In [228]:
X_test

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
7103,32,Male,5.52,1.19,1.95,4.78,8.96,24,112,7.61,High,Yes,NaN,3.14,0.568841,-0.96,2.09
5175,31,Female,9.19,3.05,2.87,5.34,6.42,235,33,11.92,Low,No,Severe,5.92,0.644178,1.58,2.73
5911,31,Male,3.82,0.72,3.49,5.52,5.02,114,125,6.57,Medium,No,NaN,4.21,1.000000,2.98,2.75
801,22,Other,11.85,3.99,3.11,1.53,7.44,76,91,12.83,Low,No,Severe,7.10,0.599156,0.56,0.98
1962,27,Male,10.74,1.53,0.29,3.55,8.84,29,178,12.49,High,Yes,Severe,1.82,0.169460,-0.84,1.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6287,25,Other,8.44,2.34,0.86,5.88,5.38,74,106,11.06,Low,No,Severe,3.20,0.379147,2.62,2.62
6230,33,Male,5.16,4.00,0.62,6.00,6.90,73,120,7.95,High,No,NaN,4.62,0.895349,1.10,2.79
5165,18,Male,10.29,5.35,1.10,1.04,8.28,247,46,12.06,Low,Yes,Severe,6.45,0.626822,-0.28,1.77
7082,35,Other,8.48,5.89,3.46,3.64,4.76,57,71,11.31,High,No,Moderate,9.35,1.000000,3.24,2.83
7129,22,Other,9.24,4.11,0.87,4.78,6.21,175,101,11.04,Low,Yes,Severe,4.98,0.538961,1.79,1.80

In [229]:
X_test[num_cols]

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
7103,32,5.52,1.19,1.95,4.78,8.96,24,112,7.61,3.14,0.568841,-0.96,2.09
5175,31,9.19,3.05,2.87,5.34,6.42,235,33,11.92,5.92,0.644178,1.58,2.73
5911,31,3.82,0.72,3.49,5.52,5.02,114,125,6.57,4.21,1.000000,2.98,2.75
801,22,11.85,3.99,3.11,1.53,7.44,76,91,12.83,7.10,0.599156,0.56,0.98
1962,27,10.74,1.53,0.29,3.55,8.84,29,178,12.49,1.82,0.169460,-0.84,1.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6287,25,8.44,2.34,0.86,5.88,5.38,74,106,11.06,3.20,0.379147,2.62,2.62
6230,33,5.16,4.00,0.62,6.00,6.90,73,120,7.95,4.62,0.895349,1.10,2.79
5165,18,10.29,5.35,1.10,1.04,8.28,247,46,12.06,6.45,0.626822,-0.28,1.77
7082,35,8.48,5.89,3.46,3.64,4.76,57,71,11.31,9.35,1.000000,3.24,2.83
7129,22,9.24,4.11,0.87,4.78,6.21,175,101,11.04,4.98,0.538961,1.79,1.80

In [230]:
X_test[cat_cols]

      gender stress_level academic_work_impact addiction_level
7103    Male         High                  Yes             NaN
5175  Female          Low                   No          Severe
5911    Male       Medium                   No             NaN
801    Other          Low                   No          Severe
1962    Male         High                  Yes          Severe
...      ...          ...                  ...             ...
6287   Other          Low                   No          Severe
6230    Male         High                   No             NaN
5165    Male          Low                  Yes          Severe
7082   Other         High                   No        Moderate
7129   Other          Low                  Yes          Severe

[1500 rows x 4 columns]

In [231]:
# fill missing categorical values using training statistics

X_test[cat_cols] = cat_imputer.transform(X_test[cat_cols])

In [232]:
X_test[cat_cols]

      gender stress_level academic_work_impact addiction_level
7103    Male         High                  Yes        Moderate
5175  Female          Low                   No          Severe
5911    Male       Medium                   No        Moderate
801    Other          Low                   No          Severe
1962    Male         High                  Yes          Severe
...      ...          ...                  ...             ...
6287   Other          Low                   No          Severe
6230    Male         High                   No        Moderate
5165    Male          Low                  Yes          Severe
7082   Other         High                   No        Moderate
7129   Other          Low                  Yes          Severe

[1500 rows x 4 columns]

In [233]:
X_test[ordinal_cols]

     stress_level addiction_level
7103         High        Moderate
5175          Low          Severe
5911       Medium        Moderate
801           Low          Severe
1962         High          Severe
...           ...             ...
6287          Low          Severe
6230         High        Moderate
5165          Low          Severe
7082         High        Moderate
7129          Low          Severe

[1500 rows x 2 columns]

In [234]:
# ordinal encoding

X_test[ordinal_cols] = ordinal_encoder.transform(X_test[ordinal_cols])

In [235]:
X_test[ordinal_cols]

      stress_level  addiction_level
7103           2.0              1.0
5175           0.0              2.0
5911           1.0              1.0
801            0.0              2.0
1962           2.0              2.0
...            ...              ...
6287           0.0              2.0
6230           2.0              1.0
5165           0.0              2.0
7082           2.0              1.0
7129           0.0              2.0

[1500 rows x 2 columns]

In [236]:
# Encoding academic_work_impact
X_test["academic_work_impact"] = X_test["academic_work_impact"].map({"No":0,"Yes":1})

In [237]:
X_test

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
7103,32,Male,5.52,1.19,1.95,4.78,8.96,24,112,7.61,2.0,1,1.0,3.14,0.568841,-0.96,2.09
5175,31,Female,9.19,3.05,2.87,5.34,6.42,235,33,11.92,0.0,0,2.0,5.92,0.644178,1.58,2.73
5911,31,Male,3.82,0.72,3.49,5.52,5.02,114,125,6.57,1.0,0,1.0,4.21,1.000000,2.98,2.75
801,22,Other,11.85,3.99,3.11,1.53,7.44,76,91,12.83,0.0,0,2.0,7.10,0.599156,0.56,0.98
1962,27,Male,10.74,1.53,0.29,3.55,8.84,29,178,12.49,2.0,1,2.0,1.82,0.169460,-0.84,1.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6287,25,Other,8.44,2.34,0.86,5.88,5.38,74,106,11.06,0.0,0,2.0,3.20,0.379147,2.62,2.62
6230,33,Male,5.16,4.00,0.62,6.00,6.90,73,120,7.95,2.0,0,1.0,4.62,0.895349,1.10,2.79
5165,18,Male,10.29,5.35,1.10,1.04,8.28,247,46,12.06,0.0,1,2.0,6.45,0.626822,-0.28,1.77
7082,35,Other,8.48,5.89,3.46,3.64,4.76,57,71,11.31,2.0,0,1.0,9.35,1.000000,3.24,2.83
7129,22,Other,9.24,4.11,0.87,4.78,6.21,175,101,11.04,0.0,1,2.0,4.98,0.538961,1.79,1.80

In [238]:
#one hot encoding 

gender_encoded_test = onehot_encoder.transform(X_test[["gender"]])

In [239]:
gender_test_df = pd.DataFrame(gender_encoded_test,
                              columns=onehot_encoder.get_feature_names_out(["gender"]),
                              index=X_test.index)

In [240]:
X_test = X_test.drop(columns=["gender"])

X_test = pd.concat([X_test, gender_test_df], axis=1)
X_test

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff,gender_Female,gender_Male,gender_Other
7103,32,5.52,1.19,1.95,4.78,8.96,24,112,7.61,2.0,1,1.0,3.14,0.568841,-0.96,2.09,0.0,1.0,0.0
5175,31,9.19,3.05,2.87,5.34,6.42,235,33,11.92,0.0,0,2.0,5.92,0.644178,1.58,2.73,1.0,0.0,0.0
5911,31,3.82,0.72,3.49,5.52,5.02,114,125,6.57,1.0,0,1.0,4.21,1.000000,2.98,2.75,0.0,1.0,0.0
801,22,11.85,3.99,3.11,1.53,7.44,76,91,12.83,0.0,0,2.0,7.10,0.599156,0.56,0.98,0.0,0.0,1.0
1962,27,10.74,1.53,0.29,3.55,8.84,29,178,12.49,2.0,1,2.0,1.82,0.169460,-0.84,1.75,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6287,25,8.44,2.34,0.86,5.88,5.38,74,106,11.06,0.0,0,2.0,3.20,0.379147,2.62,2.62,0.0,0.0,1.0
6230,33,5.16,4.00,0.62,6.00,6.90,73,120,7.95,2.0,0,1.0,4.62,0.895349,1.10,2.79,0.0,1.0,0.0
5165,18,10.29,5.35,1.10,1.04,8.28,247,46,12.06,0.0,1,2.0,6.45,0.626822,-0.28,1.77,0.0,1.0,0.0
7082,35,8.48,5.89,3.46,3.64,4.76,57,71,11.31,2.0,0,1.0,9.35,1.000000,3.24,2.83,0.0,0.0,1.0
7129,22,9.24,4.11,0.87,4.78,6.21,175,101,11.04,0.0,1,2.0,4.98,0.538961,1.79,1.80,0.0,0.0,1.0

In [241]:
# scalling num columns
X_test[num_cols]

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
7103,32,5.52,1.19,1.95,4.78,8.96,24,112,7.61,3.14,0.568841,-0.96,2.09
5175,31,9.19,3.05,2.87,5.34,6.42,235,33,11.92,5.92,0.644178,1.58,2.73
5911,31,3.82,0.72,3.49,5.52,5.02,114,125,6.57,4.21,1.000000,2.98,2.75
801,22,11.85,3.99,3.11,1.53,7.44,76,91,12.83,7.10,0.599156,0.56,0.98
1962,27,10.74,1.53,0.29,3.55,8.84,29,178,12.49,1.82,0.169460,-0.84,1.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6287,25,8.44,2.34,0.86,5.88,5.38,74,106,11.06,3.20,0.379147,2.62,2.62
6230,33,5.16,4.00,0.62,6.00,6.90,73,120,7.95,4.62,0.895349,1.10,2.79
5165,18,10.29,5.35,1.10,1.04,8.28,247,46,12.06,6.45,0.626822,-0.28,1.77
7082,35,8.48,5.89,3.46,3.64,4.76,57,71,11.31,9.35,1.000000,3.24,2.83
7129,22,9.24,4.11,0.87,4.78,6.21,175,101,11.04,4.98,0.538961,1.79,1.80

In [242]:
X_test[num_cols] = scaler.transform(X_test[num_cols])
X_test[num_cols]

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff
7103,1.037869,-0.756304,-1.301660,-0.057476,0.957050,1.729463,-1.656365,0.295869,-0.597817,-1.089832,-0.484166,-1.729463,0.480672
5175,0.845647,0.653533,-0.132014,0.744026,1.306760,-0.249724,1.506797,-1.332369,0.990286,0.328646,-0.195064,0.249724,1.368930
5911,0.845647,-1.409363,-1.597216,1.284169,1.419167,-1.340615,-0.307149,0.563806,-0.981025,-0.543871,1.170364,1.340615,1.396688
801,-0.884348,1.675378,0.459098,0.953114,-1.072519,0.545068,-0.876818,-0.136954,1.325593,0.930733,-0.367833,-0.545068,-1.059900
1962,0.076761,1.248969,-1.087854,-1.503665,0.188936,1.635958,-1.581409,1.656168,1.200313,-1.763354,-2.016748,-1.635958,0.008785
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6287,-0.307683,0.365419,-0.578492,-1.007082,1.643981,-1.060100,-0.906801,0.172205,0.673402,-1.059218,-1.212095,1.060100,1.216261
6230,1.230091,-0.894599,0.465386,-1.216169,1.718919,0.124295,-0.921792,0.460753,-0.472537,-0.334671,0.768776,-0.124295,1.452204
5165,-1.653235,1.076101,1.314323,-0.797994,-1.378515,1.199602,1.686693,-1.064431,1.041872,0.599075,-0.261667,-1.199602,0.036543
7082,1.614534,0.380785,1.653897,1.258033,0.245140,-1.543209,-1.161653,-0.549166,0.765520,2.078782,1.170364,1.543209,1.507720
7129,-0.884348,0.672741,0.534559,-0.998370,0.957050,-0.413358,0.607320,0.069152,0.666033,-0.150984,-0.598825,0.413358,0.078181

### 6 final checking train and test data before model building

In [243]:
print(X_test.shape)

X_test.head()

(1500, 19)

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff,gender_Female,gender_Male,gender_Other
7103,1.037869,-0.756304,-1.301660,-0.057476,0.957050,1.729463,-1.656365,0.295869,-0.597817,2.0,1,1.0,-1.089832,-0.484166,-1.729463,0.480672,0.0,1.0,0.0
5175,0.845647,0.653533,-0.132014,0.744026,1.306760,-0.249724,1.506797,-1.332369,0.990286,0.0,0,2.0,0.328646,-0.195064,0.249724,1.368930,1.0,0.0,0.0
5911,0.845647,-1.409363,-1.597216,1.284169,1.419167,-1.340615,-0.307149,0.563806,-0.981025,1.0,0,1.0,-0.543871,1.170364,1.340615,1.396688,0.0,1.0,0.0
801,-0.884348,1.675378,0.459098,0.953114,-1.072519,0.545068,-0.876818,-0.136954,1.325593,0.0,0,2.0,0.930733,-0.367833,-0.545068,-1.059900,0.0,0.0,1.0
1962,0.076761,1.248969,-1.087854,-1.503665,0.188936,1.635958,-1.581409,1.656168,1.200313,2.0,1,2.0,-1.763354,-2.016748,-1.635958,0.008785,0.0,1.0,0.0

In [244]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6000 entries, 5171 to 6555
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      6000 non-null   float64
 1   daily_screen_time_hours  6000 non-null   float64
 2   social_media_hours       6000 non-null   float64
 3   gaming_hours             6000 non-null   float64
 4   work_study_hours         6000 non-null   float64
 5   sleep_hours              6000 non-null   float64
 6   notifications_per_day    6000 non-null   float64
 7   app_opens_per_day        6000 non-null   float64
 8   weekend_screen_time      6000 non-null   float64
 9   stress_level             6000 non-null   float64
 10  academic_work_impact     6000 non-null   int64
 11  addiction_level          6000 non-null   float64
 12  addictive_usage_hours    6000 non-null   float64
 13  addiction_usage_ratio    6000 non-null   float64
 14  sleep_deficit            6000 non-null   float64
 15  weekend_usage_diff       6000 non-null   float64
 16  gender_Female            6000 non-null   float64
 17  gender_Male              6000 non-null   float64
 18  gender_Other             6000 non-null   float64
dtypes: float64(18), int64(1)
memory usage: 937.5 KB

In [245]:
X_train.isnull().sum()

age                        0
daily_screen_time_hours    0
social_media_hours         0
gaming_hours               0
work_study_hours           0
sleep_hours                0
notifications_per_day      0
app_opens_per_day          0
weekend_screen_time        0
stress_level               0
academic_work_impact       0
addiction_level            0
addictive_usage_hours      0
addiction_usage_ratio      0
sleep_deficit              0
weekend_usage_diff         0
gender_Female              0
gender_Male                0
gender_Other               0
dtype: int64

In [246]:
print(X_train.shape)
X_train.head()

(6000, 19)

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addictive_usage_hours,addiction_usage_ratio,sleep_deficit,weekend_usage_diff,gender_Female,gender_Male,gender_Other
5171,0.845647,-0.890757,0.566001,0.317139,0.538647,1.238562,1.161997,-1.167484,-1.213161,1.0,1,1.0,0.644997,1.170364,-1.238562,-1.351359,1.0,0.0,0.0
6534,1.037869,0.830243,1.333188,-0.371107,0.213916,-0.631536,0.232537,1.491283,0.437582,2.0,1,1.0,0.864402,0.104642,0.631536,-1.351359,0.0,0.0,1.0
1737,-0.307683,0.826402,-0.955797,-0.144596,-1.172436,0.911295,-1.026731,1.140903,1.126620,0.0,1,2.0,-0.860223,-1.237961,-0.911295,1.257898,0.0,1.0,0.0
3749,0.845647,-0.210809,0.427655,-0.423379,-0.747788,0.030790,0.682276,-0.487334,-0.627295,2.0,1,1.0,0.099036,0.357544,-0.030790,-1.601182,0.0,0.0,1.0
63,-1.268791,-0.933014,0.597443,1.240609,0.301343,-1.675675,1.206971,-0.301839,-0.822583,0.0,0,2.0,1.211367,1.170364,1.675675,0.272487,1.0,0.0,0.0

In [247]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1500 entries, 7103 to 7129
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      1500 non-null   float64
 1   daily_screen_time_hours  1500 non-null   float64
 2   social_media_hours       1500 non-null   float64
 3   gaming_hours             1500 non-null   float64
 4   work_study_hours         1500 non-null   float64
 5   sleep_hours              1500 non-null   float64
 6   notifications_per_day    1500 non-null   float64
 7   app_opens_per_day        1500 non-null   float64
 8   weekend_screen_time      1500 non-null   float64
 9   stress_level             1500 non-null   float64
 10  academic_work_impact     1500 non-null   int64
 11  addiction_level          1500 non-null   float64
 12  addictive_usage_hours    1500 non-null   float64
 13  addiction_usage_ratio    1500 non-null   float64
 14  sleep_deficit            1500 non-null   float64
 15  weekend_usage_diff       1500 non-null   float64
 16  gender_Female            1500 non-null   float64
 17  gender_Male              1500 non-null   float64
 18  gender_Other             1500 non-null   float64
dtypes: float64(18), int64(1)
memory usage: 234.4 KB

In [248]:
X_test.isnull().sum()

age                        0
daily_screen_time_hours    0
social_media_hours         0
gaming_hours               0
work_study_hours           0
sleep_hours                0
notifications_per_day      0
app_opens_per_day          0
weekend_screen_time        0
stress_level               0
academic_work_impact       0
addiction_level            0
addictive_usage_hours      0
addiction_usage_ratio      0
sleep_deficit              0
weekend_usage_diff         0
gender_Female              0
gender_Male                0
gender_Other               0
dtype: int64

## 7 Train ML Models

#### models will be trained               
 - Logistic Regression                        
 - Random Forest       
 - KNN

### 1 . Logistic regression

In [249]:
from sklearn.linear_model import LogisticRegression

# creating model
lr_model = LogisticRegression()
lr_model

LogisticRegression()

In [251]:
# train model
lr_model.fit(X_train, y_train)

LogisticRegression()

In [252]:
# predict
y_pred_lr = lr_model.predict(X_test)
y_pred_lr

array([0, 1, 0, ..., 1, 1, 1], shape=(1500,))

In [253]:
# score

lr_model.score(X_test, y_test)

0.9653333333333334